# Dzzaa

##
## Template TODO:
#1. Restrain CodeBuildRole to over permissive "*" resource -> Reference the cloudformation bucket
#2. Add all github events to codebuild
#3. Include Parameters
#4. Change CodeBuild deploy project IAM Role to separate one
#5. Create Log Group that will be attached and deleted with the CI-CD Pipeline


#TODO: Check if you can give S3:Get* Policy??

# Author: Nadar Alpenidze
##


# Insights section
# 1. To trigger the codepipeline you need to regitser a github webhook to it !!!!
# 2. CodePipeline itself doesn't have logs. It uses CodeBuilds log groups



AWSTemplateFormatVersion: "2010-09-09"
Description: "CI-CD Template example"

Parameters:
  ProjectName:
    Description: Your project name. Will be used to name the resources created with that cloudformation
    Type: String

  CodeBuildImage:
    Description: code build image
    Type: String
    Default: aws/codebuild/standard:5.0

  # RepositoryName:
  #   Description: GitHub repository name
  #   Type: String

  # GitHubOwner:
  #   Description: GitHub Repo Owner
  #   Type: String

Resources:
  # Role for CodeBuild
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LogsPermissions
                Effect: "Allow"
                Action:
                  - "cloudwatch:*"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !GetAtt CloudWatchLogGroup.Arn
              - Sid: S3BucketPermissions
                Effect: Allow
                Action:
                  - "s3:List*"
                Resource:
                  - !GetAtt DevCodePipelineArtifactStore.Arn
              - Sid: S3ObjectsPermissions
                Effect: Allow
                Action:
                  - "s3:Get*"
                Resource:
                  - !Sub ${DevCodePipelineArtifactStore.Arn}/*
                  - !GetAtt DevCodePipelineArtifactStore.Arn
                

  # Source Credentials to specify OAuth tokens for your GitHub/BitBucket provider
  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: "{{resolve:secretsmanager:github_secrets:SecretString:AWS_CI_CD_GITHUB}}"

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      # KmsKeyId: String
      LogGroupName: !Sub ${AWS::StackName}-${ProjectName}-CICD
      RetentionInDays: 30

  # The CodeBuild project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-CodeBuildProject
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
      Source:
        Type: GITHUB
        Location: https://github.com/nadar-pandologic/ci-cd-test.git
        BuildSpec: buildspec.yml
        Auth:
          Type: OAUTH
          Resource: !Ref CodeBuildSourceCredential
      TimeoutInMinutes: 10
      Triggers:
        Webhook: true #Webhooks allow you to build or set up integrations
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
            - Type: BASE_REF
              Pattern: ^refs/heads/master$
              ExcludeMatchedPattern: false
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref CloudWatchLogGroup
          Status: ENABLED
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        # - - Type: EVENT
        #     Pattern: PUSH
        #   - Type: HEAD_REF
        #     Pattern: ^refs/heads/.*
        #   - Type: FILE_PATH
        #     Pattern: READ_ME
        #     ExcludeMatchedPattern: true


 # The CodeBuild Deploy project - We use CodeBuild to run CLI commands to deploy our serverless application
  CodeBuildDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-CodeBuildDeployProject
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        EnvironmentVariables:
          - Name: ENV_NAME
            Value: dev
      Source:
        Type: CODEPIPELINE
        BuildSpec: deployspec.yml
      TimeoutInMinutes: 10
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref CloudWatchLogGroup
          Status: ENABLED
      Tags:
        - Key: Project
          Value: !Ref ProjectName
          # StreamName: String

  DevCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CodeBuildPermissions
                Effect: "Allow"
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource:
                  - !GetAtt CodeBuildProject.Arn
                  - !GetAtt CodeBuildDeployProject.Arn
              - Sid: "CloudWatchPermissions"
                Effect: "Allow"
                Action:
                  - "cloudwatch:*"
                  - "logs:*"
                Resource:
                  - "*"
              - Sid: S3Permissinos
                Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:PutObject"
                Resource:
                  - "*"
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # Artifact store bucket
  DevCodePipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-codepipeline-artifactstore-dev
      # VersioningConfiguration:
      #   Status: Enabled
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # GitHub WebHook to trigger the pipeline
  AppPipelineWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Name: AppPipelineWebhook
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "{{resolve:secretsmanager:github_secrets:SecretString:AWS_CI_CD_GITHUB}}"
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
        # - JsonPath: $.repository.name
        #   MatchEquals: '{Repo}'
      TargetPipeline: !Ref DevCodePipeline
      TargetAction: SourceAction
      TargetPipelineVersion: !GetAtt DevCodePipeline.Version
      RegisterWithThirdParty: true

  DevCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}-codepipeline-dev
      RoleArn: !GetAtt DevCodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref DevCodePipelineArtifactStore
      Stages:
      - Name: Source
        Actions:
          - 
            Name: SourceAction
            ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Provider: GitHub
              Version: '1'
            Configuration:
              Owner: nadar-pandologic
              Repo: ci-cd-test
              Branch: master
              PollForSourceChanges: false #To use GitHub webhooks
              OAuthToken: "{{resolve:secretsmanager:github_secrets:SecretString:AWS_CI_CD_GITHUB}}"
            RunOrder: 1
            OutputArtifacts:
              - Name: TestArtifact
      - Name: Build
        Actions:
          -
            Name: BuildAction
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            Configuration:
              ProjectName: !Ref CodeBuildProject
            InputArtifacts:
              - Name: TestArtifact
            OutputArtifacts:
              - Name: MyPipeline-BuildArtifact
      - Name: Deploy
        Actions:
          -
            Name: DeployAction
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            Configuration:
              ProjectName: !Ref CodeBuildDeployProject
              # PrimarySource: TestArtifact
              #EnvironmentVariables: '[{"name":"TEST_VARIABLE","value":"TEST_VALUE","type":"PLAINTEXT"},{"name":"ParamStoreTest","value":"PARAMETER_NAME","type":"PARAMETER_STORE"}]'
            InputArtifacts:
              # - Name: MyPipeline-BuildArtifact
              - Name: TestArtifact
      Tags:
        - Key: Project
          Value: !Ref ProjectName